/* *****************************************
 * CSCI 205 - Software Engineering and Design
 * Spring 2024
 * Instructor: Prof. Lily Romano / Prof. Joshua Stough
 *
 * Name: Mateo Herrera, Holiness Kerandi
 * Section: 2:00pm
 * Date: 3/20/2024
 * Time: 2:16 PM
 *
 * Project: csci205_hw1_mastermind
 * Package: org.HolinessMateo
 * Class: Solver
 *
 * Description:
 *
 * ****************************************
 */
package org.HolinessMateo;


public class Solver {

    //The number of games being simulated
    protected int numberOfGames;

    //CodeMaker to generate code
    protected CodeMaker codeMaker = new CodeMaker();

    //Code breaker used to evaluate the guesses generated by algorithms
    protected CodeBreaker codeBreaker = new CodeBreaker();

    //Array which contains the statistics from the solver simulation
    protected String[] stats = new String[6];



    public Solver(int numGames){
        this.numberOfGames = numGames;

        }

    /**
     * Calculates the average turns to win
     *
     * @param numOfTurns - {@code Integer[]} the number of turns in each game simulated
     * @return average - {@code double} the average amount of turns to win
     */
    public double calculateAverage(Integer[] numOfTurns){
        int total =0;
        for(int i: numOfTurns){
            total += i;
        }

        return total/ (double) this.numberOfGames;

    }

    /**
     * Finds the largest value in an array
     *
     * @param numOfTurns - {@code Integer[]} the number of turns to win in each game simulated
     * @return largest - {@code int} the largest value from the array
     */
    public int getLargestValue(Integer[] numOfTurns){
        int largest = numOfTurns[0];

        for (Integer numOfTurn : numOfTurns) {
            if (numOfTurn > largest) {
                largest = numOfTurn;
            }
        }

        return largest;
    }

    /**
     * Finds the smallest in array
     *
     * @param numOfTurns - {@code Integer[]} the number of turns per game simulated
     * @return smallest- {@code int} the smallest value in array
     */
    public int getSmallestValue(Integer[] numOfTurns){

        int smallest = numOfTurns[0];

        for(int i = 1; i<numOfTurns.length;i++){
            if(numOfTurns[i] < smallest){
                smallest = numOfTurns[i];
            }

        }

        return smallest;
    }

    /**
     * Formats the stats into a string
     * @param stats - {@code String[]} the statistics of the solver algorithm
     * @return s- {@code String} represents the statistics from simulation
     */
    public String resultToString(String[] stats){
        return String.format("RESULTS: \n%s - Statistics: \nNumber of games: %s \nAverage: %s \nShortest: %s \nLongest: %s \nTOTAL TIME: %s",stats[0],stats[1],stats[2],stats[3],stats[4],stats[5]);
    }

}






